# Generated by Django 4.2 on 2023-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif'), ('Bilinmiyor', 'Bilinmiyor')], default='Aktif', max_length=10)),
                ('olusturulma_tarihi', models.DateTimeField()),
                ('guncelleme_tarihi', models.DateTimeField()),
            ],
        ),
    ]
