# Generated by Django 4.2 on 2023-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
